CREATE DATABASE CUSTOMER_FEEDBACK_DB;
USE DATABASE CUSTOMER_FEEDBACK_DB;
CREATE SCHEMA ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE WAREHOUSE CUSTOMER_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE CUSTOMER_WH;

CREATE OR REPLACE TABLE CUSTOMER_REVIEWS (

PRODUCT_NAME STRING,

BRAND STRING,

CATEGORY STRING,

REVIEW_DATE DATE,

RATING FLOAT,

REVIEW_TEXT STRING,

REVIEW_TITLE STRING

);

SHOW DATABASE
SHOW TABLES;

//TOTAL REVIEWS
SELECT COUNT(*) AS TOTAL_REVIEWS
FROM CUSTOMER_REVIEWS;

//AVERAGE RATING
SELECT ROUND(AVG(RATING),2) AS AVERAGE_RATING
FROM CUSTOMER_REVIEWS;

//SENTIMENT DISTRIBUTION
SELECT
    CASE
        WHEN RATING >= 4 THEN 'Positive'
        WHEN RATING = 3 THEN 'Neutral'
        ELSE 'Negative'
    END AS SENTIMENT,
    COUNT(*) AS TOTAL
FROM CUSTOMER_REVIEWS
GROUP BY SENTIMENT
ORDER BY TOTAL DESC;

//TOP 10 BRANDS
SELECT
    BRAND,
    COUNT(*) AS TOTAL_REVIEWS
FROM CUSTOMER_REVIEWS
GROUP BY BRAND
ORDER BY TOTAL_REVIEWS DESC
LIMIT 10;

//TOP 10 PRODUCTS
SELECT
PRODUCT_NAME,
COUNT(*) AS TOTAL_REVIEWS
FROM CUSTOMER_REVIEWS
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_REVIEWS DESC
LIMIT 10;

//AVERAGE RATINGS BY BRANDS
SELECT
    BRAND,
    ROUND(AVG(RATING),2) AS AVG_RATING
FROM CUSTOMER_REVIEWS
GROUP BY BRAND
ORDER BY AVG_RATING DESC;

//MOST REVIEWED PRODUCTS
SELECT
    PRODUCT_NAME,
    COUNT(*) AS REVIEWS
FROM CUSTOMER_REVIEWS
GROUP BY PRODUCT_NAME
ORDER BY REVIEWS DESC
LIMIT 10;

//REVIEW BY CATEGORIES
SELECT
    CATEGORY,
    COUNT(*) AS TOTAL_REVIEWS
FROM CUSTOMER_REVIEWS
GROUP BY CATEGORY
ORDER BY TOTAL_REVIEWS DESC
LIMIT 10;

//HIGHEST RATED BRAND
SELECT
BRAND,
ROUND(AVG(RATING),2) AS AVG_RATING,
COUNT(*) AS REVIEWS
FROM CUSTOMER_REVIEWS
GROUP BY BRAND
HAVING COUNT(*) >= 100
ORDER BY AVG_RATING DESC;

//MONTHLY REVIEW TREND
SELECT
LEFT(REVIEW_DATE,7) AS REVIEW_MONTH,
COUNT(*) AS TOTAL_REVIEWS
FROM CUSTOMER_REVIEWS
GROUP BY LEFT(REVIEW_DATE,7)
ORDER BY REVIEW_MONTH;

SELECT *
FROM CUSTOMER_REVIEWS;